### ISSUE TITLE
devhelp

### ISSUE THREAD

**Issue by Kreyren** [kmein/niveum#53]
Hey, afaik firefox doesn't accept `extensions` as a policy (review `about:policies` for more info):

https://github.com/kmein/niveum/blob/e0a1194dae95f491221264fd965909689e004b7a/configs/browser.nix#L73

To install packages you need to use ExtensionSettings: https://github.com/Kreyren/nixos-config/blob/e4857c6a4eb628331e640c700a74fff300452ebd/nixos/users/kreyren/home/modules/web-browsers/firefox/firefox.nix#L47

Hope it helps!

**Comment by kmein** [comment]
Thank you for your idea, but I've never had any problems with the code you are referencing. See the [home-manager module](https://github.com/nix-community/home-manager/blob/1c2c5e4cabba4c43504ef0f8cc3f3dfa284e2dbb/modules/programs/firefox.nix#L915) upstream, which is what I'm using.
